import familyInHomeImage from '../assets/images/family-in-home.jpg'
import keyImage from '../assets/images/The-One.jpg'

export const JourneyMapSurvey = [
  {
    order: 0,
    key: 'decision--c00-mapping--journey--type',
    conditions: [],
    type: 'question',
    optionType: 'single',
    text: 'Where are you on your home owning journey?',
    subtext: null,
    icon: null,
    layout: 'horizontal--background',
    options: [{
      order: 1,
      key: 'journey--type--homebuyer',
      conditions: [],
      type: 'answer',
      text: "I'm looking to buy a house.",
      subtext: null,
      icon: null,
      background: keyImage,
    }, {
      order: 2,
      key: 'journey--type--homeowner',
      conditions: [],
      type: 'answer',
      text: "I'm a homeowner.",
      subtext: null,
      icon: null,
      background: familyInHomeImage,
    }],
  },
  {
    order: 1,
    key: 'decision--c00-mapping--journey--path',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homebuyer',
    }],
    type: 'question',
    optionType: 'single',
    text: 'How would you like to learn more about homebuying?',
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [{
      order: 1,
      key: 'journey--homebuyer--self-guided',
      conditions: [],
      type: 'answer',
      text: "I want to explore the homebuying toolkit.",
      subtext: 'The homebuying toolkit covers 8 steps to becoming a homeowner. It contains how-tos, videos, and checklists.',
      icon: null,
      background: keyImage,
    }, {
      order: 2,
      key: 'journey--homebuyer--custom-journey',
      conditions: [],
      type: 'answer',
      text: "I want to answer 2 questions to customize my toolkit.",
      subtext: 'Get the specific information you need from the toolkit for the step of homebuying you are in.',
      icon: null,
      background: familyInHomeImage,
    }, {
      order: 3,
      key: 'journey--homebuyer--class',
      conditions: [],
      type: 'answer',
      text: "I want to take a comprehensive homebuyers' course.",
      subtext: 'Take an in-depth homebuying class taught by a HUD-certified Homeownership Counselor!',
      icon: null,
      background: familyInHomeImage,
    },
    ],
  },
  {
    order: 2,
    key: 'decision--c00-mapping--journey--phase',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homebuyer',
    }, {
      key: 'decision--c00-mapping--journey--path',
      option: 'journey--homebuyer--custom-journey',
    }],
    type: 'question',
    optionType: 'single',
    text: 'What best describes you as a homebuyer?',
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      {
        order: 1,
        key: 'journey--homebuyer--00',
        conditions : [],
        type: 'answer',
        text: "I want to buy",
        subtext: "but I don't know where to start.",
        icon: 'PersonaStep01Diagram',
      },
      {
        order: 2,
        key: 'journey--homebuyer--01',
        conditions : [],
        type: 'answer',
        text: "I've started",
        subtext: "I have a realtor and/or have seen a few homes but I do not have a pre-approval from a lender.",
        icon: 'PersonaStep02Diagram',
      },
      {
        order: 3,
        key: 'journey--homebuyer--02',
        conditions : [],
        type: 'answer',
        text: "I'm close to or have already made an offer on a house",
        subtext: "and I have a pre-approval from a lender",
        icon: 'PersonaStep03Diagram',
      },
      {
        order: 4,
        key: 'journey--homebuyer--03',
        conditions : [],
        type: 'answer',
        text: "I've hit a wall",
        subtext: "on my homebuying journey and need help getting back on track",
        icon: null,
      },
    ]
  },
  {
    order: 3,
    key: 'decision--c00-mapping--journey--challenges',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homebuyer',
    },
    {
      key: 'decision--c00-mapping--journey--path',
      option: 'journey--homebuyer--custom-journey',
    },
    {
      key: 'decision--c00-mapping--journey--phase',
      option: 'journey--homebuyer--03',
    }],
    type: 'question',
    optionType: 'multiple',
    text: 'Which of these do you need help with?',
    subtext: null,
    icon: null,
    layout: 'vertical--icon',
    options: [
      {
        order: 1,
        key: 'journey--homebuyer--help--credit',
        conditions : [],
        type: 'answer',
        text: "credit",
        subtext: null,
        icon: 'ChallengeCredit',
      },
      {
        order: 2,
        key: 'journey--homebuyer--help--financial',
        conditions : [],
        type: 'answer',
        text: "financial readiness as a whole",
        subtext: "(debt, income, savings, credit)",
        icon: 'ChallengeFinancialReadiness',
      },
      {
        order: 3,
        key: 'journey--homebuyer--help--budget',
        conditions : [],
        type: 'answer',
        text: "how much house I can afford",
        subtext: null,
        icon: 'ChallengeHowMuch',
      },
      {
        order: 4,
        key: 'journey--homebuyer--help--dpa',
        conditions : [],
        type: 'answer',
        text: "navigating the DPA process",
        subtext: null,
        icon: 'ChallengeDPA',
      },
      {
        order: 5,
        key: 'journey--homebuyer--help--realtor',
        conditions : [],
        type: 'answer',
        text: "finding a realtor or lender to work with",
        subtext: null,
        icon: 'ChallengeFindingRealtor',
      },
      {
        order: 6,
        key: 'journey--homebuyer--help--itin',
        conditions : [],
        type: 'answer',
        text: "being an ITIN buyer",
        subtext: null,
        icon: 'ChallengeITINBuyer',
      },
    ]
  },
  {
    order: 1,
    key: 'decision--c00-mapping--journey--phase',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homeowner',
    }],
    type: 'question',
    optionType: 'single',
    text: 'What are you looking for?',
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      {
        order: 1,
        key: 'journey--homeowner--00',
        conditions : [],
        type: 'answer',
        text: "I want general resources",
        subtext: "on protecting my investment",
        icon: null,
      },
      {
        order: 2,
        key: 'journey--homeowner--01',
        conditions : [],
        type: 'answer',
        text: "I need critical support",
        subtext: "for foreclosure prevention, legal issues, etc.",
        icon: null,
      },
    ]
  },
  {
    order: 3,
    key: 'journey--homebuyer--result--00',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homebuyer',
    },
    {
      key: 'decision--c00-mapping--journey--path',
      option: 'journey--homebuyer--self-guided',
    }],
    type: 'results-toolkit',
    text: null,
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      'c01-welcome',
      'c02-what-s-your-budget',
      'c03-build-your-homebuying-team',
      'c04-get-pre-approved-for-a-mortgage',
      'c05-find-a-home-and-make-an-offer',
      'c06-finalize-your-mortgage',
      'c07-close-on-your-home',
      'c08-you-re-a-homeowner-protect-your-home',
    ],
  },
  {
    order: 3,
    key: 'journey--homebuyer--result--00',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homebuyer',
    },
    {
      key: 'decision--c00-mapping--journey--path',
      option: 'journey--homebuyer--custom-journey',
    },
    {
      key: 'decision--c00-mapping--journey--phase',
      option: 'journey--homebuyer--00',
    }],
    type: 'results-toolkit',
    text: null,
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      'c01-welcome',
      'c02-what-s-your-budget',
      'c03-build-your-homebuying-team',
      'c04-get-pre-approved-for-a-mortgage',
      'c05-find-a-home-and-make-an-offer',
      'c06-finalize-your-mortgage',
      'c07-close-on-your-home',
      'c08-you-re-a-homeowner-protect-your-home',
    ],
  },
  {
    order: 3,
    key: 'journey--homebuyer--result--01',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homebuyer',
    },
    {
      key: 'decision--c00-mapping--journey--path',
      option: 'journey--homebuyer--custom-journey',
    },
    {
      key: 'decision--c00-mapping--journey--phase',
      option: 'journey--homebuyer--01',
    }],
    type: 'results-toolkit',
    text: null,
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      'c01-welcome',
      'c03-build-your-homebuying-team',
      'c04-get-pre-approved-for-a-mortgage',
      'c05-find-a-home-and-make-an-offer',
      'c06-finalize-your-mortgage',
      'c07-close-on-your-home',
      'c08-you-re-a-homeowner-protect-your-home',
    ],
  },
  {
    order: 3,
    key: 'journey--homebuyer--result--02',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homebuyer',
    },
    {
      key: 'decision--c00-mapping--journey--path',
      option: 'journey--homebuyer--custom-journey',
    },
    {
      key: 'decision--c00-mapping--journey--phase',
      option: 'journey--homebuyer--02',
    }],
    type: 'results-toolkit',
    text: null,
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      'c01-welcome',
      'c05-find-a-home-and-make-an-offer',
      'c06-finalize-your-mortgage',
      'c07-close-on-your-home',
      'c08-you-re-a-homeowner-protect-your-home',
    ],
  },
  {
    order: 3,
    key: 'journey--homebuyer--result--03--credit',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homebuyer',
    },
    {
      key: 'decision--c00-mapping--journey--path',
      option: 'journey--homebuyer--custom-journey',
    },
    {
      key: 'decision--c00-mapping--journey--phase',
      option: 'journey--homebuyer--03',
    },
    {
      key: 'decision--c00-mapping--journey--challenges',
      option: 'journey--homebuyer--help--credit',
    }],
    type: 'results-toolkit',
    text: null,
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      'c01-welcome',
      's04-understanding-your-credit', 's05-how-to-increase-your-budget', 's00-intro-meet-the-team', 's01-start-with-a-housing-counselor',
    ],
  },
  {
    order: 3,
    key: 'journey--homebuyer--result--03--financial',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homebuyer',
    },
    {
      key: 'decision--c00-mapping--journey--path',
      option: 'journey--homebuyer--custom-journey',
    },
    {
      key: 'decision--c00-mapping--journey--phase',
      option: 'journey--homebuyer--03',
    },
    {
      key: 'decision--c00-mapping--journey--challenges',
      option: 'journey--homebuyer--help--financial',
    }],
    type: 'results-toolkit',
    text: null,
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      'c01-welcome',
      'c02-what-s-your-budget',
      's02-finding-a-realtor', 's03-choosing-a-lender',
      'c04-get-pre-approved-for-a-mortgage',
    ],
  },
  {
    order: 3,
    key: 'journey--homebuyer--result--03--budget',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homebuyer',
    },
    {
      key: 'decision--c00-mapping--journey--path',
      option: 'journey--homebuyer--custom-journey',
    },
    {
      key: 'decision--c00-mapping--journey--phase',
      option: 'journey--homebuyer--03',
    },
    {
      key: 'decision--c00-mapping--journey--challenges',
      option: 'journey--homebuyer--help--budget',
    }],
    type: 'results-toolkit',
    text: null,
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      'c01-welcome',
      'c02-what-s-your-budget',
      'c03-build-your-homebuying-team',
      'c04-get-pre-approved-for-a-mortgage',

      's00-intro-time-to-find-your-home', 's01-decide-what-you-need-and-want-in-a-home', 's02-what-to-research-about-any-home', 's03-making-an-offer',
    ],
  },
  {
    order: 3,
    key: 'journey--homebuyer--result--03--dpa',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homebuyer',
    },
    {
      key: 'decision--c00-mapping--journey--path',
      option: 'journey--homebuyer--custom-journey',
    },
    {
      key: 'decision--c00-mapping--journey--phase',
      option: 'journey--homebuyer--03',
    },
    {
      key: 'decision--c00-mapping--journey--challenges',
      option: 'journey--homebuyer--help--dpa',
    }],
    type: 'results-toolkit',
    text: null,
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      'c01-welcome',
      's03-choosing-a-lender',
    ],
  },
  {
    order: 3,
    key: 'journey--homebuyer--result--03--realtor',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homebuyer',
    },
    {
      key: 'decision--c00-mapping--journey--path',
      option: 'journey--homebuyer--custom-journey',
    },
    {
      key: 'decision--c00-mapping--journey--phase',
      option: 'journey--homebuyer--03',
    },
    {
      key: 'decision--c00-mapping--journey--challenges',
      option: 'journey--homebuyer--help--realtor',
    }],
    type: 'results-toolkit',
    text: null,
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      'c01-welcome',
      'c03-build-your-homebuying-team',
    ],
  },
  {
    order: 3,
    key: 'journey--homebuyer--result--03--itin',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homebuyer',
    },
    {
      key: 'decision--c00-mapping--journey--path',
      option: 'journey--homebuyer--custom-journey',
    },
    {
      key: 'decision--c00-mapping--journey--phase',
      option: 'journey--homebuyer--03',
    },
    {
      key: 'decision--c00-mapping--journey--challenges',
      option: 'journey--homebuyer--help--itin',
    }],
    type: 'results-toolkit',
    text: null,
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      'c01-welcome',
      's00-intro-meet-the-team', 's01-start-with-a-housing-counselor',
    ],
  },

  {
    order: 3,
    key: 'journey--homeowner--result--00',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homeowner',
    },
    {
      key: 'decision--c00-mapping--journey--phase',
      option: 'journey--homeowner--00',
    }],
    type: 'results-toolkit',
    text: null,
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      // 'c01-welcome',
      'c08-you-re-a-homeowner-protect-your-home',
    ],
  },
  {
    order: 3,
    key: 'journey--homeowner--result--01',
    conditions: [{
      key: 'decision--c00-mapping--journey--type',
      option: 'journey--type--homeowner',
    },
    {
      key: 'decision--c00-mapping--journey--phase',
      option: 'journey--homeowner--01',
    }],
    type: 'results-toolkit',
    text: null,
    subtext: null,
    icon: null,
    layout: 'horizontal--icon',
    options: [
      // 'c01-welcome',
      's07-help-to-keep-your-home',
    ],
  },
  {
    order: 3,
    key: 'journey--homebuyer--path--class',
    conditions: [{
        key: 'decision--c00-mapping--journey--type',
        option: 'journey--type--homebuyer',
      },
      {
        key: 'decision--c00-mapping--journey--path',
        option: 'journey--homebuyer--class',
      },
    ],
    type: 'results-about-class',
    text: null,
    subtext: null,
  },
]